public class janu
{
   public static final integer discount=75;
    private static final integer discount1=75;
    public static integer discount2=75;
      static integer discount3=75;
    
    public static void main1(integer i, integer j, integer k, integer l)
    {
        //discount=i;
        //discount1=j;
        discount2=k;
        discount3=l;
         system.debug(discount); 
        system.debug(discount1); 
        system.debug(discount2); 
        system.debug(discount3); 
        
    }
     
    public static void main2()
    {
        
    }
    
}