public class ThirdDevConsoleClass 
{
    /*
 public static void firstMethod()
     {
            
          Map<string,integer> abcd1= new Map<string,integer>();
         abcd1.put('alpana', 12);
         abcd1.put('goldee', 13);
         abcd1.put('jyoti', 14);
         //integer aa=abcd1.get('jyoti');
         system.debug(abcd1.get('jyoti'));

   Map<integer,integer> testmap= new Map<integer,integer>();
            testmap.put(1, 100);
         testmap.put(2, 100);
         testmap.put(3, 200);
             //integeMap<integer,string> abcd1= new Map<ineger,string>(11>='bittu',12>='mamta');
         //system.debug(abcd1.get(11));
         system.debug(testmap);
         system.debug(testmap.get(3));
         integer aa=testmap.size();
         testmap.clear();
         system.debug(aa);
         system.debug(testmap);
         aa=testmap.size();
         
        
      }
*/
}