public class ThirdDevConsoleClass1 {
    public static void firstmethod()
    {
    /*
         integer count = 15;
        while (count<20)
        {
           system.debug(count);
            count++;
        }
*/

        
        /*
        integer i1 = 12345;
     integer i2 = 65;
     integer i3 = 89;
     system.debug(i1);
     system.debug(i2);
     system.debug(i3);
        
        long l1 = 5623l;
        long l2 = 8923l;
        system.debug(l1);
        system.debug(l2);
        
        Double d = 2.14;
        double pi = 3.14;
        system.debug(d);
        system.debug(pi);

        
        ID i = '02u7F000001g9Nx';
        string s = i;
        system.debug(i);
        system.debug(s.substring(0,s.length()-3));
        integer k =s.length();
        system.debug(k);
        system.debug(s.substring(0,17));
        
        
        Date d = Date.newInstance(2018, 4, 12);
        System.debug(d);

        
        
        DateTime dt = DateTime.newInstance(2018, 4, 16, 13, 40, 20);
         system.debug(dt);
   
        
        
        Time t = Time.newInstance(10, 16, 20, 23);
        system.debug(t);
        
        integer X = 20;
        integer Y = 10;
        boolean b = X>Y;
        system.debug(b);
        
        
        Object X = 20;
        Object Y = 'Alpana';
        Object Z = 10.54;
        Double d = (Double)Z;
        
        system.debug(x);
        system.debug(Y);
        system.debug(Z);
      
        Blob b = Blob.valueOf('dfghhjkl/.,mnbvsdfghjklasdfghjkl;zxcvbbnm,./wertyuiop');
        system.debug(b);
        system.debug(b.toString());

       
        
        List<Integer> Bittu = new List <Integer> ();
        Bittu.add(123);
        Bittu.add(66666);
        Bittu.add(754444444);
        Bittu.add(100);
        //Bittu.remove(1);
        Bittu.sort();
        for(integer i:Bittu)//for each 
        {
           integer count=0;
          system.debug(i);  
count++;
            count=count++;
            system.debug(count);
        }

        //system.debug(BittuList);
         //system.debug(BittuList.get(2));
        // system.debug(Bittu);
         //Bittu.set(0,10000);
//system.debug(Bittu);
       /*
        boolean a=Bittu.isEmpty();
        system.debug(a); 
        system.debug(Bittu);
        if(!a)
        {
            
            integer pos=Bittu.size(); 
            system.debug(pos);
            Bittu.add(10000);
        }
        Bittu.clear();
        a=Bittu.isEmpty();
        system.debug(a); 
       system.debug(Bittu);
        
        
    //List <String> BittuList = new List <String> ();
       //BittuList.add('goldee');
        //BittuList.add('mamta');
        //BittuList.add('batuk');
        //system.debug(BittuList);        
        
        
        integer count = 1;
        do
        {
           system.debug(count);
            count++; 
                       
        }
        while(count<15);
           
        integer count = 1;
        while(count<20)
        {
            system.debug(count);
            count++;
        }
 
        integer count = 15;
        do
        {
           system.debug(count);
            count++; 
                       
        }
        while(count<20);
         
        
        for(integer i=10,j=6; j<i; j++)
        {
           system.debug(j+1); 
        }
           */
        
    }
    
    
}